### ISSUE TITLE
s -h帮助信息不准确

### ISSUE THREAD

**Issue by heimanba** [devsapp/sae#41]
![image](https://user-images.githubusercontent.com/5129967/183955756-d5f63eea-f7e1-4ab2-aaac-766fd89d92ca.png)

**Comment by Joycepy** [comment]
![image](https://user-images.githubusercontent.com/38881498/184054369-56a8d742-05f8-4b3c-ada9-fc5ce48fb87a.png)
已修改custom comand信息
